[project]
name = "xpyxl"
version = "0.11.0"
description = "Create styled excel reports with declarative python."
readme = "README.md"
authors = [{ name = "dakixr", email = "dakixr@gmail.com" }]
requires-python = ">=3.12"
keywords = ["excel", "xlsx", "report", "spreadsheet", "openpyxl", "xlsxwriter"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Office/Business :: Financial :: Spreadsheet",
]
dependencies = ["openpyxl>=3.1.5", "xlsxwriter>=3.1.0"]

[project.urls]
Homepage = "https://github.com/dakixr/xpyxl"
Repository = "https://github.com/dakixr/xpyxl"
Issues = "https://github.com/dakixr/xpyxl/issues"

[project.optional-dependencies]
reportlab = [
    "reportlab>=4.0.0",
]

[dependency-groups]
dev = [
    "pillow>=12.1.0",
    "pyright>=1.1.406",
    "pytest>=9.0.2",
    "reportlab>=4.0.0",
]

[build-system]
requires = ["hatchling==1.27.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/xpyxl"]

[tool.hatch.build.targets.sdist]
include = ["src/xpyxl"]
